//DATA
export const SET_DATA                   = "SET_DATA";
export const DATA_FILLED_SUCCESS        = "DATA_FILLED_SUCCESS";
export const DATA_FILLED_ERROR          = "DATA_FILLED_ERROR";

//SELECTDATA
export const SET_DEFAULT_SELECTED_DATA  = "SET_DEFAULT_SELECTED_DATA";
export const SET_FACT_SELECTED          = "SET_FACT_SELECTED";
export const SET_MARKET_SELECTED        = "SET_MARKET_SELECTED";
export const SET_CATEGORY_SELECTED      = "SET_CATEGORY_SELECTED";
export const SET_LAST_PERIOD            = "SET_LAST_PERIOD_SELECTED";
export const SELECTED_DATA_SUCCESS      = "SELECTED_DATA_SUCCESS";
export const SELECTED_DATA_ERROR        = "SELECTED_DATA_ERROR";
