export const characters = [
  "Mario",
  "Luigi",
  "Peach",
  "Yoshi",
  "Rosalina",
  "Bowser",
  "Bowser Jr.",
  "Wario",
  "Donkey Kong",
  "Diddy Kong",
  "Toad",
  "Daisy",
  "Waluigi",
  "Boo",
  "Link",
  "Zelda",
  "Ganon"
];

export const gameSeries = [
  "Super Mario",
  "Yoshi's Woolly World",
  "The Legend of Zelda",
  "Breath of the Wild",
  "Animal Crossing",
  "Star Fox",
  "Metroid",
  "F-Zero",
  "Pikmin",
  "Punch Out",
  "Wii Fit",
  "Kid Icarus",
  "Classic Nintendo",
  "Mii",
  "Splatoon",
  "Mario Sports Superstars",
  "Pokemon",
  "Kirby",
  "BoxBoy!",
  "Fire Emblem",
  "Xenoblade",
  "Earthbound",
  "Chibi Robo",
  "Sonic",
  "Bayonetta",
  "Pac-man",
  "Megaman",
  "Street fighter",
  "Monster Hunter",
  "Shovel Knight",
  "Final Fantasy",
  "Kellogs"
];

export const amiiboSeries = [
  "Super Smash Bros.",
  "Super Mario Bros.",
  "8-bit Mario",
  "Yoshi's Woolly World",
  "Skylanders",
  "Legend Of Zelda",
  "Animal Crossing",
  "Metroid",
  "Splatoon",
  "Mario Sports Superstars",
  "Pokemon",
  "Kirby",
  "BoxBoy!",
  "Fire Emblem",
  "Chibi-Robo!",
  "Monster Hunter",
  "Shovel Knight",
  "Pikmin",
  "Kellogs"
];
