import React from "react";
import styles from "./Albums.module.css";

function Album({ name, images, id, release_date, total_tracks }) {
  return (
    <li className={styles.album} key={id}>
      <h3>{name}</h3>
      <img src={images[0].url} alt={name} />
      <p>Released on {new Date(release_date).toLocaleDateString()}</p>
      <p>
        {total_tracks} {total_tracks === 1 ? "track" : "tracks"}
      </p>
    </li>
  );
}

export default function Albums({ id, albums }) {
  return <ul className={styles.albums}>{albums.map(Album)}</ul>;
}

Albums.defaultProps = {
  albums: [
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/0zcNtUZ2oEpRmiDuWBFvcX",
      },
      href: "https://api.spotify.com/v1/albums/0zcNtUZ2oEpRmiDuWBFvcX",
      id: "0zcNtUZ2oEpRmiDuWBFvcX",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/182176cfcab47e634e2d91443584a1ef9147197f",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/4d91963894dfa05bb0b8c7373a97dc587146ea16",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/c2eba1b5609469774d8e70409089dc9aef2b83d2",
          width: 64,
        },
      ],
      name: "One More Light Live",
      release_date: "2017-12-15",
      release_date_precision: "day",
      total_tracks: 16,
      type: "album",
      uri: "spotify:album:0zcNtUZ2oEpRmiDuWBFvcX",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/5Eevxp2BCbWq25ZdiXRwYd",
      },
      href: "https://api.spotify.com/v1/albums/5Eevxp2BCbWq25ZdiXRwYd",
      id: "5Eevxp2BCbWq25ZdiXRwYd",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/24b1591bc4ecc8fe201465a9c1bf1af96c93224d",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/4a5a7737db8a500dd89ff8dd5bb9d993f481c97b",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/8dffc0613d103efc7255ce435f6ab7ebec022f84",
          width: 64,
        },
      ],
      name: "One More Light",
      release_date: "2017-05-19",
      release_date_precision: "day",
      total_tracks: 10,
      type: "album",
      uri: "spotify:album:5Eevxp2BCbWq25ZdiXRwYd",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/6hU9JCoqq4GjYq86dQ1o9b",
      },
      href: "https://api.spotify.com/v1/albums/6hU9JCoqq4GjYq86dQ1o9b",
      id: "6hU9JCoqq4GjYq86dQ1o9b",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/ecf066e65db6d8dbd208b9411b138a47c17a2bfd",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/c1e9e3f0789bcb02f35d2d220cda25e20f5951cd",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/d3a2e822dc2b27fc423caecc7a6330cdb9f50868",
          width: 64,
        },
      ],
      name: "The Hunting Party - A cappellas and Instrumentals",
      release_date: "2014-06-16",
      release_date_precision: "day",
      total_tracks: 22,
      type: "album",
      uri: "spotify:album:6hU9JCoqq4GjYq86dQ1o9b",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/3XB2yloP7l00tEUmaODtVi",
      },
      href: "https://api.spotify.com/v1/albums/3XB2yloP7l00tEUmaODtVi",
      id: "3XB2yloP7l00tEUmaODtVi",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/0fd0e5c52b212771f6f882f75880757cfa2e57a1",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/c0bd529ddec9a5dae9be0d6f956777739a18507d",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/3e6c0488170f66fff2095d86f632ae9dd63f6304",
          width: 64,
        },
      ],
      name: "The Hunting Party",
      release_date: "2014-06-13",
      release_date_precision: "day",
      total_tracks: 12,
      type: "album",
      uri: "spotify:album:3XB2yloP7l00tEUmaODtVi",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/2FUsvD1bw53HGOjAg56vRD",
      },
      href: "https://api.spotify.com/v1/albums/2FUsvD1bw53HGOjAg56vRD",
      id: "2FUsvD1bw53HGOjAg56vRD",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/a29415c0de8aedf124b4617a453dd941c5b3ec05",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/f9195b09b639bfa62948bf7920894e9bc351a416",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/9ab2c1c83562200295bb87182bce55abfba93ae7",
          width: 64,
        },
      ],
      name: "Recharged",
      release_date: "2013-10-25",
      release_date_precision: "day",
      total_tracks: 14,
      type: "album",
      uri: "spotify:album:2FUsvD1bw53HGOjAg56vRD",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/7qRKpkP0jSOlBMLYZhAMCh",
      },
      href: "https://api.spotify.com/v1/albums/7qRKpkP0jSOlBMLYZhAMCh",
      id: "7qRKpkP0jSOlBMLYZhAMCh",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/c16211f3c6f1c22517e0ee0f09e7deccf64999a7",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/35f0f6982d10e36eface94e0609f251142f2c09f",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/91d7c756888db5eaa64169809a9d502d8520032b",
          width: 64,
        },
      ],
      name: "Living Things: A cappellas and Instrumentals",
      release_date: "2012-06-25",
      release_date_precision: "day",
      total_tracks: 22,
      type: "album",
      uri: "spotify:album:7qRKpkP0jSOlBMLYZhAMCh",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/4XHIjbhjRmqWlosjj5rqSI",
      },
      href: "https://api.spotify.com/v1/albums/4XHIjbhjRmqWlosjj5rqSI",
      id: "4XHIjbhjRmqWlosjj5rqSI",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/967661595be2ffdd741e8e7c72cbd975dfc263b5",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/1c6ab5f28338c09671ba8f0d71989ec2f22a9d23",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/85957b735b208f2f33808007a747234279519cf1",
          width: 64,
        },
      ],
      name: "Living Things",
      release_date: "2012-06-20",
      release_date_precision: "day",
      total_tracks: 12,
      type: "album",
      uri: "spotify:album:4XHIjbhjRmqWlosjj5rqSI",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/0hJ3A7sih1AXDoMjXHLr7Q",
      },
      href: "https://api.spotify.com/v1/albums/0hJ3A7sih1AXDoMjXHLr7Q",
      id: "0hJ3A7sih1AXDoMjXHLr7Q",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/77db68f503bd575fc0608acee86f68e3e25a6615",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/d885409f68a3579793b10903b7bdc320d3a1031f",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/dc2eb03df79b6be588278e96cd75acbf7bdaf5fb",
          width: 64,
        },
      ],
      name: "A Thousand Suns Live Around the World",
      release_date: "2012-06-19",
      release_date_precision: "day",
      total_tracks: 10,
      type: "album",
      uri: "spotify:album:0hJ3A7sih1AXDoMjXHLr7Q",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/7IYqppCBhR5z9z8JqgXuxi",
      },
      href: "https://api.spotify.com/v1/albums/7IYqppCBhR5z9z8JqgXuxi",
      id: "7IYqppCBhR5z9z8JqgXuxi",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/bab2abeba8e3b172d175095143c5718da3a1f73b",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/d8f368989b8f452c552d33daf93930982a64154f",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/f0a4ba2f8cfb142227866bec975fdb80fe2ec081",
          width: 64,
        },
      ],
      name: "Minutes To Midnight Live Around The World",
      release_date: "2012-06-12",
      release_date_precision: "day",
      total_tracks: 12,
      type: "album",
      uri: "spotify:album:7IYqppCBhR5z9z8JqgXuxi",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/4flcwtqnLoKZJ2wrCp1aJq",
      },
      href: "https://api.spotify.com/v1/albums/4flcwtqnLoKZJ2wrCp1aJq",
      id: "4flcwtqnLoKZJ2wrCp1aJq",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/238d0066cbcb27449ca1ee06db731811817ddfb5",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/42e1e1cb1d272641eb3a06f2db2cd4109e7ef51b",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/dff53e6a7c0a772223571f373697b88cdf4d2912",
          width: 64,
        },
      ],
      name: "Meteora Live Around the World",
      release_date: "2012-06-05",
      release_date_precision: "day",
      total_tracks: 7,
      type: "album",
      uri: "spotify:album:4flcwtqnLoKZJ2wrCp1aJq",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/1FiRqhpAowNK8gTl5sOhxZ",
      },
      href: "https://api.spotify.com/v1/albums/1FiRqhpAowNK8gTl5sOhxZ",
      id: "1FiRqhpAowNK8gTl5sOhxZ",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/f1227b8c34ce6f70f65ab9bbf56aee4cb6737697",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/c79226889b347f827c0d2e122973a35473e299be",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/a2187d3c27724f2042d5414b10acc4738090c448",
          width: 64,
        },
      ],
      name: "Hybrid Theory Live Around the World",
      release_date: "2012-05-31",
      release_date_precision: "day",
      total_tracks: 8,
      type: "album",
      uri: "spotify:album:1FiRqhpAowNK8gTl5sOhxZ",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/4fy0SXW5G8evBCo2A3kn02",
      },
      href: "https://api.spotify.com/v1/albums/4fy0SXW5G8evBCo2A3kn02",
      id: "4fy0SXW5G8evBCo2A3kn02",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/01b96f5444b5e9e4a2dd8d582b10911640c8ebec",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/4f99a368dbcfa221050c7b4675acb66206e4843a",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/3656b93f4ff09852e99035da617966d69a514ed8",
          width: 64,
        },
      ],
      name: "A Thousand Suns (Bonus Edition)",
      release_date: "2010-09-13",
      release_date_precision: "day",
      total_tracks: 21,
      type: "album",
      uri: "spotify:album:4fy0SXW5G8evBCo2A3kn02",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/5uvXx5ZQswNRFCdHR521YZ",
      },
      href: "https://api.spotify.com/v1/albums/5uvXx5ZQswNRFCdHR521YZ",
      id: "5uvXx5ZQswNRFCdHR521YZ",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/38fed8308958f74c76e71f75f38063ccaea4505b",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/895ad925a25ca737cc70ff022b1f4f46c200958a",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/3546fad5f461e7efa82aa6a5ed8a664764363b81",
          width: 64,
        },
      ],
      name: "A Thousand Suns",
      release_date: "2010-09-10",
      release_date_precision: "day",
      total_tracks: 15,
      type: "album",
      uri: "spotify:album:5uvXx5ZQswNRFCdHR521YZ",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/7IjD1U0ig5h7nwXYtexLok",
      },
      href: "https://api.spotify.com/v1/albums/7IjD1U0ig5h7nwXYtexLok",
      id: "7IjD1U0ig5h7nwXYtexLok",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/c89436fe4d34edea1de28b08e28c62a8e6f6de14",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/49b388a0e03ca98bd0bd80c1f1198a867048d06c",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/e9f79ee7e41f975c8d09724caaef0a9c6cab2596",
          width: 64,
        },
      ],
      name: "Road to Revolution (Live at Milton Keynes)",
      release_date: "2008-11-24",
      release_date_precision: "day",
      total_tracks: 18,
      type: "album",
      uri: "spotify:album:7IjD1U0ig5h7nwXYtexLok",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/72seWTJF9U5SljizfyF2ZK",
      },
      href: "https://api.spotify.com/v1/albums/72seWTJF9U5SljizfyF2ZK",
      id: "72seWTJF9U5SljizfyF2ZK",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/f16a98a5c703039f911b82965debafbf22466c7b",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/412b5e8823bfe46e2488fa6bcaa8753f57164b44",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/4da2a75e6c8cecede0492a55ebc3ff0cb54e05dc",
          width: 64,
        },
      ],
      name: "Road to Revolution (Live at Milton Keynes)",
      release_date: "2008-11-21",
      release_date_precision: "day",
      total_tracks: 18,
      type: "album",
      uri: "spotify:album:72seWTJF9U5SljizfyF2ZK",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/7pgs38iLfEqUtwgCRgvbND",
      },
      href: "https://api.spotify.com/v1/albums/7pgs38iLfEqUtwgCRgvbND",
      id: "7pgs38iLfEqUtwgCRgvbND",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/deb48b2781de449175ff7865da3bb249652fc28f",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/25c88542f89cfcd842e62b6c3851518fe0eca6f6",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/98ab8557be40ee514e38af4f6f1f7af8f5c447fc",
          width: 64,
        },
      ],
      name: "Minutes to Midnight",
      release_date: "2007-05-14",
      release_date_precision: "day",
      total_tracks: 14,
      type: "album",
      uri: "spotify:album:7pgs38iLfEqUtwgCRgvbND",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/2tlTBLz2w52rpGCLBGyGw6",
      },
      href: "https://api.spotify.com/v1/albums/2tlTBLz2w52rpGCLBGyGw6",
      id: "2tlTBLz2w52rpGCLBGyGw6",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/deb48b2781de449175ff7865da3bb249652fc28f",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/25c88542f89cfcd842e62b6c3851518fe0eca6f6",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/98ab8557be40ee514e38af4f6f1f7af8f5c447fc",
          width: 64,
        },
      ],
      name: "Minutes to Midnight",
      release_date: "2007-05-14",
      release_date_precision: "day",
      total_tracks: 12,
      type: "album",
      uri: "spotify:album:2tlTBLz2w52rpGCLBGyGw6",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/108CU1JE5mXMvYM5jul8TX",
      },
      href: "https://api.spotify.com/v1/albums/108CU1JE5mXMvYM5jul8TX",
      id: "108CU1JE5mXMvYM5jul8TX",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/dd7779f2840cdeeb4f12d0717678b7da54e8556c",
          width: 639,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/6a0c27c39642066c32419f0306f94092950b13db",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/0d98cecee419216f715bb65153048b3b7dd137ef",
          width: 64,
        },
      ],
      name: "Minutes to Midnight",
      release_date: "2007-05-14",
      release_date_precision: "day",
      total_tracks: 14,
      type: "album",
      uri: "spotify:album:108CU1JE5mXMvYM5jul8TX",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/0ZBE7rVC0zKFVt5osvXlnz",
      },
      href: "https://api.spotify.com/v1/albums/0ZBE7rVC0zKFVt5osvXlnz",
      id: "0ZBE7rVC0zKFVt5osvXlnz",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/ec0c10fa92f001a8ad11062014f2191dd4c5e2c3",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/676c5fd828f75b20ab92167a9655c28d001d7c24",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/d7c4f5afd4c81b3d4c6ec5c3354e7f999ba16b40",
          width: 64,
        },
      ],
      name: "Live in Texas",
      release_date: "2003-11-18",
      release_date_precision: "day",
      total_tracks: 12,
      type: "album",
      uri: "spotify:album:0ZBE7rVC0zKFVt5osvXlnz",
    },
    {
      album_group: "album",
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz",
          },
          href: "https://api.spotify.com/v1/artists/6XyY86QOPPrYVGvF9ch6wz",
          id: "6XyY86QOPPrYVGvF9ch6wz",
          name: "Linkin Park",
          type: "artist",
          uri: "spotify:artist:6XyY86QOPPrYVGvF9ch6wz",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA",
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/0f7R0jf0pcTb6K6IVVPcMD",
      },
      href: "https://api.spotify.com/v1/albums/0f7R0jf0pcTb6K6IVVPcMD",
      id: "0f7R0jf0pcTb6K6IVVPcMD",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/fe26cf70090dbd2898307ca5f6fd65cd837fe995",
          width: 640,
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/3a9bad60f804dc28ec8864dcd763ebe75984a7c8",
          width: 300,
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/2ea58dd384a20c8cac3040a2429ad15f504072b7",
          width: 64,
        },
      ],
      name: "Meteora (Bonus Edition)",
      release_date: "2003-03-24",
      release_date_precision: "day",
      total_tracks: 16,
      type: "album",
      uri: "spotify:album:0f7R0jf0pcTb6K6IVVPcMD",
    },
  ],
};
