export const FETCH_ANIME = 'FETCH_ANIME';
export const FETCHING_ANIME = 'FETCHING_ANIME';
export const FETCH_SINGLE_ANIME = 'FETCH_SINGLE_ANIME';
export const FETCHING_SINGLE_ANIME = 'FETCHING_SINGLE_ANIME';